### ISSUE TITLE
Install command doesn't work

### ISSUE THREAD

**Issue by welcoMattic** [QuickBox/DockBox#1]
I just clone this repo, then launch `box install` script to install plex.

This is the output:

```
$ ./box install plex
find: ‘/usr/local/bin/quickbox/package/install’: No such file or directory
Package plex not found
```

The `box` script seems to not be updated :(

**Comment by JMSDOnline** [comment]
This was contributed by a previous user, unless there is specifically articles posted in regards to this being officially supported, then it is not. This repo along with a few others will be getting removed soon. one word on this, it will more than likely get ported into QuickBox_Pro, which is currently alpha and it is not advised to use unless you know exactly what you're doing.
